// Copyright (c) Meta Platforms, Inc. and affiliates.

// This software may be used and distributed according to the terms of the
// GNU General Public License version 2.
#ifndef __P2DQ_INTF_H
#define __P2DQ_INTF_H

#include <stdbool.h>
#ifndef __kptr
#ifdef __KERNEL__
#error "__kptr_ref not defined in the kernel"
#endif
#define __kptr
#endif

#ifndef __KERNEL__
typedef unsigned char u8;
typedef unsigned int u32;
typedef unsigned long long u64;
#endif


enum consts {
	MAX_CPUS		= 512,
	MAX_NUMA_NODES		= 64,
	MAX_LLCS		= 64,
	MAX_DSQS_PER_LLC	= 8,
	MAX_LLC_SHARDS		= 32,
	MAX_TASK_PRIO		= 39,
	MAX_TOPO_NODES		= 1024,

	NSEC_PER_USEC		= 1000ULL,
	NSEC_PER_MSEC		= (1000ULL * NSEC_PER_USEC),
	MSEC_PER_SEC		= 1000ULL,
	NSEC_PER_SEC		= NSEC_PER_MSEC * MSEC_PER_SEC,

	MIN_SLICE_USEC		= 10ULL,
	MIN_SLICE_NSEC		= (10ULL * NSEC_PER_USEC),

	LOAD_BALANCE_SLACK	= 20ULL,

	P2DQ_MIG_DSQ		= 1LLU << 60,
	P2DQ_INTR_DSQ		= 1LLU << 32,

	// kernel definitions
	CLOCK_BOOTTIME		= 7,

	DEBUG_EVENTS_BUF_SIZE	= 4096,
};

enum p2dq_timers_defs {
	EAGER_LOAD_BALANCER_TMR,
	MAX_TIMERS,
};

enum p2dq_lb_mode {
	PICK2_LOAD,
	PICK2_NR_QUEUED,
};

enum stat_idx {
	P2DQ_STAT_ATQ_ENQ,
	P2DQ_STAT_ATQ_REENQ,
	P2DQ_STAT_DIRECT,
	P2DQ_STAT_DSQ_SAME,
	P2DQ_STAT_DSQ_CHANGE,
	P2DQ_STAT_IDLE,
	P2DQ_STAT_LB_SELECT,
	P2DQ_STAT_LB_DISPATCH,
	P2DQ_STAT_LLC_MIGRATION,
	P2DQ_STAT_NODE_MIGRATION,
	P2DQ_STAT_KEEP,
	P2DQ_STAT_ENQ_CPU,
	P2DQ_STAT_ENQ_LLC,
	P2DQ_STAT_ENQ_INTR,
	P2DQ_STAT_ENQ_MIG,
	P2DQ_STAT_SELECT_PICK2,
	P2DQ_STAT_DISPATCH_PICK2,
	P2DQ_STAT_WAKE_PREV,
	P2DQ_STAT_WAKE_LLC,
	P2DQ_STAT_WAKE_MIG,
	P2DQ_NR_STATS,
};

enum scheduler_mode {
	MODE_DEFAULT,
	MODE_PERF,
	MODE_EFFICIENCY,
};

/* Debug/Trace event types - each specific log location gets its own context-aware enum */
enum debug_event_type {
	TRACE_EVENT_ENQUEUE_TASK_WEIGHT_SLICE_VTIME_LLC_VTIME,
	TRACE_EVENT_DISPATCH_CPU_MIN_VTIME_DSQ_ATQ,
	TRACE_EVENT_ATQ_DISPATCHING_WITH_MIN_VTIME,
	TRACE_EVENT_RUNNING_PID_CPU_MIGRATION_LLC_MIGRATION,
	TRACE_EVENT_STOPPING_TASK_WEIGHT_SLICE_USED_SCALED,
	TRACE_EVENT_SELECT_CPU_PID_COMM_PREV_TO_NEW_IDLE,
	DEBUG_EVENT_ATQ_CREATED_FOR_LLC,
	DEBUG_EVENT_ATQ_FAILED_TO_GET_PID,
	TRACE_EVENT_ATQ_INSERT_TASK_TO_QUEUE,
	TRACE_EVENT_PICK2_CPU_FIRST_SECOND_LOAD,
	TRACE_EVENT_DSQ_INDEX_INCREMENT_FOR_TASK,
	TRACE_EVENT_DSQ_INDEX_DECREMENT_FOR_TASK,
	TRACE_EVENT_PREFERRED_CPU_IDLE_FOR_TASK,
	DEBUG_EVENT_CONFIG_NODE_CONFIGURED,
	DEBUG_EVENT_CONFIG_CPU_NODE_LLC_INITIALIZED,
	DEBUG_EVENT_CPU_IS_BIG_CORE,
	DEBUG_EVENT_LOAD_BALANCE_LLC_CONTEXT,
	DEBUG_EVENT_LOAD_BALANCE_TOTAL_LOAD_INTERACTIVE,
	DEBUG_EVENT_LOAD_BALANCE_AUTOSLICE_IDEAL_SUM,
	DEBUG_EVENT_LOAD_BALANCE_AUTOSLICE_INTERACTIVE_SLICE,
	DEBUG_EVENT_TIMER_STOPPED_FOR_KEY,
	DEBUG_EVENT_CONFIG_CREATING_AFFINITY_CPU_DSQ,
};

/* Debug event record - stores raw data with variable args, formatted by Rust */
struct debug_event {
	u64 timestamp;
	u32 event_type;
	u64 args[6];  /* Variable arguments based on event type */
} __attribute__((packed));

#endif /* __P2DQ_INTF_H */
