name: 'Install Nix with caching'
description: 'Install Nix and configure caching on both self-hosted and GitHub Hosted runners'
inputs:
  cachix-auth-token:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - uses: cachix/cachix-action@v14
      name: Configure Cachix
      with:
        name: sched-ext
        authToken: '${{ inputs.cachix-auth-token }}'
        skipAddingSubstituter: false
        useDaemon: false
